# Generated by Django 3.2.14 on 2022-07-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='tx',
            field=models.ImageField(default='uploads/tx/tx.jpeg', upload_to='uploads/tx/%Y%m%d', verbose_name='用户头像'),
        ),
    ]
